Leaf: Clarify the prerelease-flag
CycloneDX/transparency-exchange-api pull request #75
Opened 2024-11-18 12:50 UTC by oej

Close #44

2024-11-18 12:51 UTC, oej commented
Ping @vpetersson

2024-11-18 20:11 UTC, ppkarwasz commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
Should we stress the fact that this applies to **non-deployed** releases, regardless of the naming.

For example [`org.apache.logging.log4j:log4j-core:3.0.0-beta3`](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/3.0.0-beta3) does not count as pre-release, since we are not allowed by Maven Central to modify it.

2024-11-18 20:59 UTC, oej commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
I would definitely set something named "-beta3" as a prerelease. If you modify something, that's always a new release with a new leaf. Maybe we need to be clearer in the text.

The thing with the flag change was that in some cases a pre-release is upgraded to final release after testing, without ANY changes. That's just another release behaviour.

2024-11-19 07:51 UTC, madpah commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
@ppkarwasz makes a good point. We need to be clear on _our_ definition of what constitutes a pre-release in TEA.

2024-11-19 07:55 UTC, madpah commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
The concept of "pre-release" will mean different things to different parties:

- Maven: As per example from @ppkarwasz - it _was_ published; it _cannot_ be modified; it is _not_ intended for use in Production systems
- COTS: E.g. Windows Server 3030 RC (fictitious) - it _was_ published; it _cannot_ be modified; it is _not_ intended for use in Production systems

For me both these examples would be considered as `pre-releases` by their Manufacturers.

2024-11-19 08:20 UTC, oej commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
We have had long discussions about this before, but can of course restart if needed.

2024-11-19 09:11 UTC, madpah commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
My only point really is that our definition is not clear in the docs we have. Not that it hasn't been discussed already 😉

2024-11-19 09:22 UTC, vpetersson commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
Some thoughts on this:

* We need to be dynamic here -- in some workflows per-releases will not be published, but in other workflows they will (e.g. promoted). Thus, as long as we allow for `PATCH`ing the LEAF to toggle this boolean, we should be good and cover both workflows.
* NIT: `s/alfa/alpha/g` and `s/prerelease/pre-release/g`

2024-11-20 13:09 UTC, madpah requested changes

2024-11-20 13:09 UTC, madpah commented on tea-leaf/tea-leaf.md
> +very agnostic to how a "version" is indicated - semver, vers, name, hash or anything else.
```suggestion
very agnostic as to how a "version" is indicated - semver, vers, name, hash or anything else.
```

2024-11-20 13:09 UTC, madpah commented on tea-leaf/tea-leaf.md
> +- __Uuid__ unique for this object
We've called this an `identifier` (which is of type UUID) in the OpenAPI Spec - we need to align in either direction.

2024-11-20 13:09 UTC, madpah commented on tea-leaf/tea-leaf.md
> +- __Prerelease__: A boolean flag indicating a pre-release (beta, rc)
```suggestion
- __Pre-Release__: A boolean flag indicating a pre-release (beta, rc)
```

2024-11-20 13:09 UTC, madpah commented on tea-leaf/tea-leaf.md
> +## Handling the Prerelease flag
```suggestion
## Handling the Pre-Release flag
```

2024-11-20 13:09 UTC, madpah commented on tea-leaf/tea-leaf.md
> +The Prerelease flag is used to indicate that this is not a final release. For a given Leaf with a UUID, the flag
```suggestion
The Pre-Release flag is used to indicate that this is not a final release. For a given Leaf with a UUID, the flag
```

2024-11-20 13:09 UTC, madpah commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
```suggestion
can be set to indicate a "test", "beta", "alpha" or similar non-deployed release. It can only be set when
```

2024-11-20 14:58 UTC, madpah commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
Does everyone agree with @vpetersson's conclusion? Does that work for you @ppkarwasz?

I think we still need to add wording to clarify in Docs.

2024-11-22 10:14 UTC, oej commented on tea-leaf/tea-leaf.md
> +- __Uuid__ unique for this object
Agree

2024-11-22 10:20 UTC, oej commented on tea-leaf/tea-leaf.md
> +can be set to indicate a "test", "beta", "alfa" or similar non-deployed release. It can only be set when
Seems like we have a conclusion. What text is needed to clarify more? I tried to be bit fuzzy in the text to not hardcode to a specific example. The flag is meant as a warning to not use this release. We can rename it to "not-recommended" or something along those lines to avoid the discussions about all variants of "beta", "pre-release", "test-release" etc. Just

2025-01-09 09:22 UTC, oej commented on tea-leaf/tea-leaf.md
> +- __Uuid__ unique for this object
We can align in a later request

2025-02-11 08:44 UTC, merged