fix: aligned TEI examples to specification
CycloneDX/transparency-exchange-api pull request #88
Opened 2024-11-20 16:45 UTC by madpah

Resolves #87

2024-11-20 16:50 UTC, ppkarwasz commented
Maybe the examples are right and the specification should be modified. The first element you might expect in a URN is the authority.

2024-11-20 16:55 UTC, madpah commented
Fair comment @ppkarwasz - @oej - thoughts on the order of the items in TEI?

2024-11-21 07:06 UTC, oej commented
The TYPE needs to come first as we can come up with TEI types that has another resolution than DNS in the future.

2024-11-21 07:21 UTC, ppkarwasz commented
Aren't there two `<type>`s then?

- One tells us how to find the TEA service.
- One is part of the identifier

For example:

- `urn:tei:dns:logging.apache.org:purl:pkg:maven/org.apache.logging/log4j-core` tells the user to use the DNS discovery mechanism we were talking about.
- `urn:tei:purl:pkg:maven/org.apache.logging/log4j-core` tells the user to use an ecosystem-dependent mechanism to find the TEA server.

Alternatively, to keep it simple:

- The TEI identifier **only** refers to the DNS mechanism and we have: `urn:tei:logging.apache.org:purl:pkg:maven/org.apache.logging/log4j-core`.
- If a user doesn't find a TEI, but find the PURL `pkg:maven/org.apache.logging/log4j-core`, he can still use a TEA service, but the resolution mechanism is ecosystem-dependent.

2024-11-21 07:43 UTC, oej commented
I don't like restricting the TEI to ONLY DNS resolution. There will be a lot of work establishing the TEI as a common identifier and having to restart that work for new non-DNS types will be hard. Better to have one single identifier and be able to extend it.

But you are not wrong that the PURL could be used for TEA discovery too, especially for stuff that is not packaged. That is a discussion we need to bring up in the PURL wg, I just haven't had time for it. We mentioned it briefly as an option in the SBOM forum vulnerabilities wg meeting. I'm thinking of commercial software and open source projects not primarily being distributed as packages (like C code).

2024-11-21 08:53 UTC, oej commented
We really need to clarify the intent of the TEI. But that's another PR

2024-11-21 08:56 UTC, oej commented
Created issue #89 to clarify the TEI URN more. It's definitely needed for registration with IANA/IETF

2024-11-22 10:13 UTC, oej approved these changes
Time to merge. Discussions are moved to other tickets. Thank you for this PR!

2024-11-22 10:17 UTC, oej requested changes

2024-11-22 10:17 UTC, oej commented on discovery/readme.md
> +urn:tei:purl:org.cyclonedx:pkg:pypi/cyclonedx-python-lib@8.4.0?extension=whl&qualifier=py3-none-any
The domain should be "cyclonedx.org"

2024-11-22 10:17 UTC, oej commented on discovery/readme.md
> +urn:tei:uuid:cyclonedx.org:d4d9f54a-abcf-11ee-ac79-1a52914d44b1
Resolved in other conversation. The UUID includes version.

2024-11-22 11:26 UTC, madpah commented
Requested changes made @oej

2024-11-22 13:23 UTC, oej approved these changes
Great work. Thank you Paul!

2024-12-06 10:49 UTC, merged